//! Copyright 2025 β ORI Inc.Canada All Rights Reserved.
//! Author: Awase Khirni Syed
//! Product Name: β ORI Inc. Hexagonal Architecture Generator in Rust
//! Rust Onion Architecture/Hexagonal Architecture Scaffolder Project

//! scaffold.rs — creates the complete `hexagonal_architecture_rust`
//! workspace skeleton (all directories + files with starter contents).
//!
//! Usage:
//!     rustc scaffold.rs -o scaffold
//!     ./scaffold                     # target: ./hexagonal_architecture_rust
//!     ./scaffold path/to/dir         # custom target directory
//!
//! Properties:
//!   * std-only — this script itself has no crates.io dependencies
//!   * idempotent — existing files are skipped, never overwritten
//!   * marks *.sh scripts executable on Unix
//!   * the generated skeleton is a valid Cargo workspace:
//!         cargo build --workspace   # compiles
//!         cargo test -p domain      # two real tests pass

use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

const DEFAULT_ROOT: &str = "hexagonal_architecture_rust";

/// Every file as `(path relative to the root, contents)`.
/// Parent directories are created on demand.
///
/// Entries flagged `[extra]` are `mod.rs` files the blueprint *implied*
/// but didn't spell out — they are required for the Rust module tree
/// (and hence `cargo build`) to work.
const FILES: &[(&str, &str)] = &[
    // ══════════════════════════ workspace root ══════════════════════════
    (
        "Cargo.toml",
        r##"[workspace]
resolver = "2"
members = [
    "crates/domain",
    "crates/application",
    "crates/infrastructure",
    "crates/api",
    "crates/config",
    "crates/shared",
    "crates/bin/api",
    "crates/bin/worker",
    "crates/bin/migrate",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# internal crates
domain         = { path = "crates/domain" }
application    = { path = "crates/application" }
infrastructure = { path = "crates/infrastructure" }
api            = { path = "crates/api" }
config         = { path = "crates/config" }
shared         = { path = "crates/shared" }

# shared tooling
tokio              = { version = "1",   features = ["full"] }
serde              = { version = "1",   features = ["derive"] }
serde_json         = "1"
uuid               = { version = "1",   features = ["v4", "serde"] }
chrono             = { version = "0.4", features = ["serde"] }
async-trait        = "0.1"
thiserror          = "2"
anyhow             = "1"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
"##,
    ),
    (
        "Cargo.lock",
        r##"# This file is automatically generated by Cargo.
# It is not intended for manual editing.
version = 3
"##,
    ),
    (
        ".cargo/config.toml",
        r##"# Cargo configuration (invocation flags — profiles live in Cargo.toml).
# https://doc.rust-lang.org/cargo/reference/config.html

[term]
color = "always"

# Examples — uncomment as needed:
# [build]
# jobs = 8
# rustflags = ["-W", "clippy::pedantic"]
# [env]
# RUST_BACKTRACE = "1"
"##,
    ),
    (
        ".gitignore",
        r##"# Rust
/target

# Runtime logs (keep folder, ignore contents)
/logs/*
!/logs/.gitkeep

# Local secrets (keep folder, ignore contents)
/secrets/*
!/secrets/.gitignore
!/secrets/.env.example
.env

# IDE / OS
.idea/
.vscode/
.DS_Store
"##,
    ),
    (
        ".dockerignore",
        r##"target
logs
secrets
scripts
.git
docs
deployments
tests
benches
*.md
"##,
    ),
    (
        ".rustfmt.toml",
        r##"max_width = 100
hard_tabs = false
edition = "2021"
# nightly-only niceties:
# imports_granularity = "Module"
# group_imports = "StdExternalCrate"
"##,
    ),
    (
        ".clippy.toml",
        r##"# https://doc.rust-lang.org/clippy/configuration.html
msrv = "1.83"
"##,
    ),
    (
        "rust-toolchain.toml",
        r##"[toolchain]
channel = "1.83.0"
components = ["rustfmt", "clippy"]
profile = "minimal"
"##,
    ),
    (
        "config.yaml",
        r##"# Default configuration (overridden by config.<profile>.yaml and APP__* env vars)
server:
  host: "0.0.0.0"
  port: 8080

database:
  url: "postgres://postgres:postgres@localhost:5432/hexagonal"
  max_connections: 10

security:
  jwt_secret: "change-me-in-prod"
  access_token_ttl_secs: 3600

observability:
  log_level: "info"
  metrics_enabled: true
  tracing_enabled: false
"##,
    ),
    (
        "config.dev.yaml",
        r##"# Development overrides
server:
  port: 8080
observability:
  log_level: "debug"
"##,
    ),
    (
        "config.prod.yaml",
        r##"# Production overrides — secrets come from the environment, not this file.
database:
  max_connections: 50
observability:
  log_level: "warn"
  tracing_enabled: true
"##,
    ),
    // Real TAB characters are guaranteed via escapes, so recipes survive copy/paste.
    (
        "Makefile",
        concat!(
            "# Task runner (GNU Make) — run `make help`.\n",
            ".DEFAULT_GOAL := help\n",
            ".PHONY: help build run test lint fmt check migrate seed docker-build openapi\n",
            "\n",
            "help:           ## Show this help\n",
            "\t@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \\\n",
            "\t| awk 'BEGIN {FS = \":.*?## \"}; {printf \"  %-14s %s\\n\", $$1, $$2}'\n",
            "\n",
            "build:          ## Build the whole workspace\n",
            "\tcargo build --workspace\n",
            "\n",
            "run:            ## Run the API server\n",
            "\tcargo run -p api-server\n",
            "\n",
            "test:           ## Run all tests\n",
            "\tcargo test --workspace\n",
            "\n",
            "lint:           ## Clippy, warnings as errors\n",
            "\tcargo clippy --workspace --all-targets -- -D warnings\n",
            "\n",
            "fmt:            ## Format all code\n",
            "\tcargo fmt --all\n",
            "\n",
            "check:          ## Fast type-check\n",
            "\tcargo check --workspace\n",
            "\n",
            "migrate:        ## Apply SQL migrations\n",
            "\t./scripts/migrate.sh\n",
            "\n",
            "seed:           ## Seed the database\n",
            "\t./scripts/seed.sh\n",
            "\n",
            "docker-build:   ## Build the production image\n",
            "\tdocker build -f deployments/docker/Dockerfile -t hexagonal-api:0.1.0 .\n",
            "\n",
            "openapi:        ## Dump the OpenAPI document\n",
            "\t./scripts/generate-openapi.sh\n",
        ),
    ),
    (
        "README.md",
        r##"# hexagonal_architecture_rust

Hexagonal (ports & adapters) architecture template for a Rust workspace.

## Layout

| Crate                     | Layer      | Responsibility                              |
|---------------------------|------------|---------------------------------------------|
| `crates/domain`           | Core       | Entities, value objects, events, **ports**  |
| `crates/application`      | Use cases  | Orchestration, DTOs, commands & queries     |
| `crates/infrastructure`   | Adapters   | Postgres, Redis, JWT, Argon2, Kafka, …      |
| `crates/api`              | Inbound    | Axum handlers, middleware, OpenAPI          |
| `crates/config`           | —          | figment-based configuration                 |
| `crates/shared`           | —          | `AppError`, `AppResult`, pagination, …      |
| `crates/bin/*`            | Roots      | `api-server`, `worker`, `migrate` binaries  |

## Quickstart

    cargo build --workspace
    cargo test -p domain

See `docs/ARCHITECTURE.md`, `docs/DEVELOPMENT.md`, and `docs/adr/`.
"##,
    ),
    // ══════════════════════════ crates/domain ══════════════════════════
    (
        "crates/domain/Cargo.toml",
        r##"[package]
name = "domain"
description = "Core business logic — pure, framework-free"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
thiserror   = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
"##,
    ),
    (
        "crates/domain/src/lib.rs",
        r##"//! Domain layer — the innermost hexagon.
//!
//! Pure business logic: entities, value objects, domain events,
//! ports (traits for dependency inversion) and domain errors.
//!
//! This crate must stay framework-free: no sqlx, no axum, no tokio.

pub mod auth;
pub mod shared;
pub mod user;
"##,
    ),
    (
        "crates/domain/src/user/mod.rs",
        r##"//! User bounded context.

pub mod entity;
pub mod error;
pub mod event;
pub mod port;
pub mod value_object;
"##,
    ),
    (
        "crates/domain/src/user/entity/mod.rs",
        r##"//! Entities of the user context.

pub mod role;
pub mod user;
"##,
    ),
    (
        "crates/domain/src/user/entity/user.rs",
        r##"//! `User` entity — the aggregate root of the user context.

use crate::user::entity::role::Role;
use crate::user::value_object::email::Email;
use crate::user::value_object::user_status::UserStatus;

/// Aggregate root of the user bounded context.
///
/// Keep it behaviour-rich: invariants live here — not in controllers.
#[derive(Debug, Clone)]
pub struct User {
    pub id: uuid::Uuid,
    pub email: Email,
    pub name: String,
    pub role: Role,
    pub status: UserStatus,
}

impl User {
    /// Registers a new user, enforcing invariants and recording a
    /// [`UserCreated`](crate::user::event::user_created::UserCreated) event.
    pub fn register(
        id: uuid::Uuid,
        email: Email,
        name: String,
    ) -> Result<Self, crate::user::error::user_error::UserError> {
        if name.trim().is_empty() {
            return Err(crate::user::error::user_error::UserError::InvalidName);
        }
        let _ = (id, email, name);
        todo!("construct the User (Active, role User) and record UserCreated")
    }
}
"##,
    ),
    (
        "crates/domain/src/user/entity/role.rs",
        r##"//! `Role` enum.

/// Roles a user can hold.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Role {
    /// Full administrative access.
    Admin,
    /// Regular end user.
    User,
}
"##,
    ),
    (
        "crates/domain/src/user/value_object/mod.rs",
        r##"//! Value objects of the user context.

pub mod email;
pub mod user_status;
"##,
    ),
    (
        "crates/domain/src/user/value_object/email.rs",
        r##"//! `Email` value object — "parse, don't validate".

use std::fmt;

use crate::user::error::user_error::UserError;

/// A validated e-mail address.
///
/// Construct through [`Email::parse`]: an `Email` that exists is *proof*
/// the address is well-formed — no later re-validation is needed.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Email(String);

impl Email {
    /// Parses and validates an e-mail address ("parse, don't validate").
    pub fn parse(raw: impl Into<String>) -> Result<Self, UserError> {
        let raw = raw.into();
        let (local, domain) = raw.split_once('@').ok_or(UserError::InvalidEmail)?;

        if local.is_empty() || !domain.contains('.') {
            return Err(UserError::InvalidEmail);
        }

        Ok(Self(raw))
    }

    /// The address as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for Email {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}
"##,
    ),
    (
        "crates/domain/src/user/value_object/user_status.rs",
        r##"//! `UserStatus` value object.

/// Lifecycle status of a [`User`](crate::user::entity::user::User).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UserStatus {
    /// Active and able to log in.
    Active,
    /// Temporarily blocked.
    Suspended,
    /// Soft-deleted.
    Deleted,
}
"##,
    ),
    (
        "crates/domain/src/user/event/mod.rs",
        r##"//! Domain events of the user context.

pub mod user_created;
pub mod user_updated;

/// Every event the user context can emit.
#[derive(Debug, Clone)]
pub enum UserEvent {
    /// A user was created.
    Created(user_created::UserCreated),
    /// A user was updated.
    Updated(user_updated::UserUpdated),
}
"##,
    ),
    (
        "crates/domain/src/user/event/user_created.rs",
        r##"//! `UserCreated` domain event.

/// Emitted when a new user registers.
#[derive(Debug, Clone)]
pub struct UserCreated {
    pub user_id: uuid::Uuid,
    pub email: String,
}
"##,
    ),
    (
        "crates/domain/src/user/event/user_updated.rs",
        r##"//! `UserUpdated` domain event.

/// Emitted when an existing user changes.
#[derive(Debug, Clone)]
pub struct UserUpdated {
    pub user_id: uuid::Uuid,
}
"##,
    ),
    (
        "crates/domain/src/user/port/mod.rs",
        r##"//! [PORTS] — traits the outside world must implement (dependency inversion).

pub mod event_publisher;
pub mod password_service;
pub mod user_repository;
"##,
    ),
    (
        "crates/domain/src/user/port/user_repository.rs",
        r##"//! `trait UserRepository` — the persistence port.

use async_trait::async_trait;

use crate::shared::error::domain_error::DomainError;
use crate::shared::value_object::pagination::Pagination;
use crate::user::entity::user::User;

/// Persistence boundary for the user aggregate.
#[async_trait]
pub trait UserRepository: Send + Sync {
    async fn save(&self, user: &User) -> Result<(), DomainError>;
    async fn find_by_id(&self, id: uuid::Uuid) -> Result<Option<User>, DomainError>;
    async fn find_all(&self, page: Pagination) -> Result<Vec<User>, DomainError>;
    async fn delete(&self, id: uuid::Uuid) -> Result<(), DomainError>;
}
"##,
    ),
    (
        "crates/domain/src/user/port/password_service.rs",
        r##"//! `trait PasswordService` — hashing port.

use async_trait::async_trait;

use crate::shared::error::domain_error::DomainError;

/// Hashes and verifies passwords. Implemented by infrastructure (Argon2).
#[async_trait]
pub trait PasswordService: Send + Sync {
    async fn hash(&self, plain: &str) -> Result<String, DomainError>;
    async fn verify(&self, plain: &str, hash: &str) -> Result<bool, DomainError>;
}
"##,
    ),
    (
        "crates/domain/src/user/port/event_publisher.rs",
        r##"//! `trait EventPublisher` — outbound messaging port.

use async_trait::async_trait;

use crate::shared::error::domain_error::DomainError;
use crate::user::event::UserEvent;

/// Publishes domain events to the outside world (at-least-once).
#[async_trait]
pub trait EventPublisher: Send + Sync {
    async fn publish(&self, event: UserEvent) -> Result<(), DomainError>;
}
"##,
    ),
    (
        "crates/domain/src/user/error/mod.rs",
        r##"//! Errors of the user context.

pub mod user_error;
"##,
    ),
    (
        "crates/domain/src/user/error/user_error.rs",
        r##"//! thiserror-based domain errors for the user context.

/// Errors of the user bounded context.
#[derive(Debug, thiserror::Error)]
pub enum UserError {
    #[error("invalid email address")]
    InvalidEmail,
    #[error("user not found: {0}")]
    NotFound(uuid::Uuid),
    #[error("name must be non-empty")]
    InvalidName,
}
"##,
    ),
    (
        "crates/domain/src/auth/mod.rs",
        r##"//! Auth bounded context.

pub mod entity;
pub mod error;
pub mod port;
"##,
    ),
    (
        "crates/domain/src/auth/entity/mod.rs",
        r##"//! Entities of the auth context.

pub mod session;
"##,
    ), // [extra]
    (
        "crates/domain/src/auth/entity/session.rs",
        r##"//! `Session` entity.

use chrono::{DateTime, Utc};

/// An authenticated session for a user.
#[derive(Debug, Clone)]
pub struct Session {
    pub id: uuid::Uuid,
    pub user_id: uuid::Uuid,
    pub expires_at: DateTime<Utc>,
}
"##,
    ),
    (
        "crates/domain/src/auth/port/mod.rs",
        r##"//! Ports of the auth context.

pub mod auth_repository;
pub mod token_service;
"##,
    ), // [extra]
    (
        "crates/domain/src/auth/port/auth_repository.rs",
        r##"//! `trait AuthRepository` — session persistence port.

use async_trait::async_trait;

use crate::auth::entity::session::Session;
use crate::auth::error::auth_error::AuthError;

/// Persistence boundary for sessions.
#[async_trait]
pub trait AuthRepository: Send + Sync {
    async fn save(&self, session: &Session) -> Result<(), AuthError>;
    async fn find_by_id(&self, id: uuid::Uuid) -> Result<Option<Session>, AuthError>;
    async fn revoke(&self, id: uuid::Uuid) -> Result<(), AuthError>;
}
"##,
    ),
    (
        "crates/domain/src/auth/port/token_service.rs",
        r##"//! `trait TokenService` — token issuing/verification port.

use async_trait::async_trait;

use crate::auth::error::auth_error::AuthError;

/// Issues and verifies bearer tokens.
#[async_trait]
pub trait TokenService: Send + Sync {
    async fn issue(&self, user_id: uuid::Uuid, ttl_secs: i64) -> Result<String, AuthError>;
    async fn verify(&self, token: &str) -> Result<uuid::Uuid, AuthError>;
}
"##,
    ),
    (
        "crates/domain/src/auth/error/mod.rs",
        r##"//! Errors of the auth context.

pub mod auth_error;
"##,
    ), // [extra]
    (
        "crates/domain/src/auth/error/auth_error.rs",
        r##"//! thiserror-based errors for the auth context.

/// Errors of the auth bounded context.
#[derive(Debug, thiserror::Error)]
pub enum AuthError {
    #[error("invalid or expired token")]
    InvalidToken,
    #[error("session expired")]
    SessionExpired,
}
"##,
    ),
    (
        "crates/domain/src/shared/mod.rs",
        r##"//! Shared kernel — deliberately kept tiny.

pub mod error;
pub mod port;
pub mod value_object;
"##,
    ),
    (
        "crates/domain/src/shared/value_object/mod.rs",
        r##"//! Shared value objects.

pub mod pagination;
pub mod user_id;
"##,
    ), // [extra]
    (
        "crates/domain/src/shared/value_object/user_id.rs",
        r##"//! `UserId` value object.

/// Typed user identifier — avoids "primitive obsession".
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct UserId(pub uuid::Uuid);

impl From<uuid::Uuid> for UserId {
    fn from(id: uuid::Uuid) -> Self {
        Self(id)
    }
}
"##,
    ),
    (
        "crates/domain/src/shared/value_object/pagination.rs",
        r##"//! `Pagination` value object.

/// Page request parameters.
#[derive(Debug, Clone, Copy)]
pub struct Pagination {
    /// 1-based page number.
    pub page: u32,
    /// Items per page.
    pub per_page: u32,
}

impl Default for Pagination {
    fn default() -> Self {
        Self { page: 1, per_page: 20 }
    }
}
"##,
    ),
    (
        "crates/domain/src/shared/error/mod.rs",
        r##"//! Shared domain errors.

pub mod domain_error;
"##,
    ), // [extra]
    (
        "crates/domain/src/shared/error/domain_error.rs",
        r##"//! Base error type for the domain core.

/// Errors raised by the domain, independent of any adapter.
#[derive(Debug, thiserror::Error)]
pub enum DomainError {
    #[error("entity not found: {0}")]
    NotFound(String),
    #[error("validation failed: {0}")]
    Validation(String),
    #[error("conflict: {0}")]
    Conflict(String),
}
"##,
    ),
    (
        "crates/domain/src/shared/port/mod.rs",
        r##"//! Shared ports.

pub mod unit_of_work;
"##,
    ), // [extra]
    (
        "crates/domain/src/shared/port/unit_of_work.rs",
        r##"//! `trait UnitOfWork` — transactional boundary port.

use async_trait::async_trait;

use crate::shared::error::domain_error::DomainError;

/// Groups repository operations into a single transaction.
#[async_trait]
pub trait UnitOfWork: Send + Sync {
    async fn begin(&self) -> Result<(), DomainError>;
    async fn commit(&self) -> Result<(), DomainError>;
    async fn rollback(&self) -> Result<(), DomainError>;
}
"##,
    ),
    (
        "crates/domain/tests/user_entity_test.rs",
        r##"//! Integration tests for the domain (no I/O needed — that's the point).

use domain::user::value_object::email::Email;

#[test]
fn rejects_invalid_email() {
    assert!(Email::parse("not-an-email").is_err());
}

#[test]
fn accepts_valid_email() {
    assert!(Email::parse("alice@example.com").is_ok());
}
"##,
    ),
    // ═══════════════════════ crates/application ═══════════════════════
    (
        "crates/application/Cargo.toml",
        r##"[package]
name = "application"
description = "Use cases — orchestration of the domain"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
domain = { workspace = true }
serde  = { workspace = true }
uuid   = { workspace = true }
"##,
    ),
    (
        "crates/application/src/lib.rs",
        r##"//! Application layer — use cases that orchestrate the domain.
//!
//! Depends only on the `domain` crate (through its ports);
//! knows nothing about HTTP, SQL or message brokers.

pub mod auth;
pub mod shared;
pub mod user;
"##,
    ),
    (
        "crates/application/src/user/mod.rs",
        r##"//! User use cases.

pub mod command;
pub mod dto;
pub mod query;
"##,
    ),
    (
        "crates/application/src/user/command/mod.rs",
        r##"//! Write side — commands (CQS).

pub mod create_user;
pub mod delete_user;
pub mod update_user;
"##,
    ),
    (
        "crates/application/src/user/command/create_user.rs",
        r##"//! `CreateUserUseCase`.

use std::sync::Arc;

use domain::shared::error::domain_error::DomainError;
use domain::user::port::password_service::PasswordService;
use domain::user::port::user_repository::UserRepository;

use crate::user::dto::create_user_dto::CreateUserDto;
use crate::user::dto::user_response_dto::UserResponseDto;

/// Command-side use case: create a user (CQS).
pub struct CreateUserUseCase<R, P> {
    repository: Arc<R>,
    password_service: Arc<P>,
}

impl<R, P> CreateUserUseCase<R, P>
where
    R: UserRepository,
    P: PasswordService,
{
    pub fn new(repository: Arc<R>, password_service: Arc<P>) -> Self {
        Self {
            repository,
            password_service,
        }
    }

    /// Executes the use case against its ports.
    pub async fn execute(&self, dto: CreateUserDto) -> Result<UserResponseDto, DomainError> {
        // Reference the ports while the body is still a TODO.
        let _ = (&dto, &self.repository, &self.password_service);
        todo!("validate → hash password → User::register → save → publish UserCreated")
    }
}
"##,
    ),
    (
        "crates/application/src/user/command/update_user.rs",
        r##"//! `UpdateUserUseCase`.

// TODO: load → apply changes → save → publish `UserUpdated`.
"##,
    ),
    (
        "crates/application/src/user/command/delete_user.rs",
        r##"//! `DeleteUserUseCase`.

// TODO: load → enforce delete rules → change status → publish event.
"##,
    ),
    (
        "crates/application/src/user/query/mod.rs",
        r##"//! Read side — queries (CQS).

pub mod get_user_by_id;
pub mod list_users;
"##,
    ),
    (
        "crates/application/src/user/query/get_user_by_id.rs",
        r##"//! `GetUserByIdUseCase`.

// TODO: fetch through `UserRepository`, map to `UserResponseDto`.
"##,
    ),
    (
        "crates/application/src/user/query/list_users.rs",
        r##"//! `ListUsersUseCase`.

// TODO: paginated read through `UserRepository`.
"##,
    ),
    (
        "crates/application/src/user/dto/mod.rs",
        r##"//! DTOs for the user use cases.

pub mod create_user_dto;
pub mod user_response_dto;
"##,
    ),
    (
        "crates/application/src/user/dto/create_user_dto.rs",
        r##"//! Input DTO for `CreateUserUseCase`.

/// Input for creating a user.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct CreateUserDto {
    pub email: String,
    pub name: String,
    pub password: String,
}
"##,
    ),
    (
        "crates/application/src/user/dto/user_response_dto.rs",
        r##"//! DTO returned by user commands/queries.

use domain::user::entity::user::User;

/// Read model returned to the adapters.
#[derive(Debug, Clone, serde::Serialize)]
pub struct UserResponseDto {
    pub id: uuid::Uuid,
    pub email: String,
    pub name: String,
}

impl From<&User> for UserResponseDto {
    fn from(user: &User) -> Self {
        Self {
            id: user.id,
            email: user.email.to_string(),
            name: user.name.clone(),
        }
    }
}
"##,
    ),
    (
        "crates/application/src/auth/mod.rs",
        r##"//! Auth use cases.

pub mod command;
pub mod query;
"##,
    ),
    (
        "crates/application/src/auth/command/mod.rs",
        r##"//! Auth commands.

pub mod login_user;
pub mod register_user;
"##,
    ), // [extra]
    (
        "crates/application/src/auth/command/register_user.rs",
        r##"//! `RegisterUserUseCase` — sign-up: creates the user and starts a session.

// TODO: hash password, create user, issue token, persist session.
"##,
    ),
    (
        "crates/application/src/auth/command/login_user.rs",
        r##"//! `LoginUserUseCase` — verifies credentials and issues a token.

// TODO: verify via `PasswordService`, issue via `TokenService`.
"##,
    ),
    (
        "crates/application/src/auth/query/mod.rs",
        r##"//! Auth queries.

pub mod verify_token;
"##,
    ), // [extra]
    (
        "crates/application/src/auth/query/verify_token.rs",
        r##"//! `VerifyTokenUseCase`.

// TODO: delegate to `TokenService::verify` and load the session.
"##,
    ),
    (
        "crates/application/src/shared/mod.rs",
        r##"//! Cross-cutting application concerns.

pub mod decorator;
"##,
    ),
    (
        "crates/application/src/shared/decorator/mod.rs",
        r##"//! Use-case decorators — wrap any use case with extra behaviour.

pub mod audit;
pub mod cache;
"##,
    ), // [extra]
    (
        "crates/application/src/shared/decorator/cache.rs",
        r##"//! Caching decorator — memoizes query results.

// TODO: wrap a query use case and serve hits from the cache port.
"##,
    ),
    (
        "crates/application/src/shared/decorator/audit.rs",
        r##"//! Audit decorator — records who invoked which use case, and when.

// TODO: wrap a command use case and append to an audit log.
"##,
    ),
    (
        "crates/application/tests/create_user_use_case_test.rs",
        r##"//! Integration tests for `CreateUserUseCase`.

// TODO: drive the use case with in-memory fakes for its ports
// (see `infrastructure::persistence::inmemory`).
"##,
    ),
    // ═════════════════════ crates/infrastructure ═════════════════════
    (
        "crates/infrastructure/Cargo.toml",
        r##"[package]
name = "infrastructure"
description = "Outbound adapters — persistence, cache, security, messaging, observability"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
domain      = { workspace = true }
async-trait = { workspace = true }
tokio       = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
serde       = { workspace = true }
tracing     = { workspace = true }
sqlx        = { version = "0.8", default-features = false, features = [
    "runtime-tokio",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
] }

# TODO: enable as the adapters are implemented:
# redis                       = "0.27"
# jsonwebtoken                = "9"
# argon2                      = "0.5"
# rdkafka                     = "0.36"
# lapin                       = "2"
# metrics-exporter-prometheus = "0.15"
# opentelemetry-otlp          = "0.27"
"##,
    ),
    (
        "crates/infrastructure/src/lib.rs",
        r##"//! Infrastructure layer — outbound adapters.
//!
//! Everything that talks to the outside world lives here: Postgres
//! persistence, Redis cache, JWT & Argon2 security, Kafka/RabbitMQ
//! publishers, logging and observability.

pub mod cache;
pub mod logging;
pub mod messaging;
pub mod observability;
pub mod persistence;
pub mod security;
"##,
    ),
    (
        "crates/infrastructure/src/persistence/mod.rs",
        r##"//! Persistence adapters.

pub mod inmemory;
pub mod migration;
pub mod postgres;
"##,
    ),
    (
        "crates/infrastructure/src/persistence/postgres/mod.rs",
        r##"//! PostgreSQL adapters (sqlx).

pub mod auth_repository;
pub mod mapper;
pub mod model;
pub mod unit_of_work;
pub mod user_repository;
"##,
    ),
    (
        "crates/infrastructure/src/persistence/postgres/model/mod.rs",
        r##"//! Row models (database representations).

pub mod user_model;
"##,
    ), // [extra]
    (
        "crates/infrastructure/src/persistence/postgres/model/user_model.rs",
        r##"//! `sqlx::FromRow` struct for the `users` table.
//!
//! This is the *database* representation — never let it leak past
//! the mapper into the domain.

/// Row model for `users`.
#[derive(Debug, sqlx::FromRow)]
pub struct UserModel {
    pub id: uuid::Uuid,
    pub email: String,
    pub name: String,
    pub role: String,
    pub status: String,
    pub password_hash: String,
}
"##,
    ),
    (
        "crates/infrastructure/src/persistence/postgres/mapper/mod.rs",
        r##"//! Model ↔ entity mappers.

pub mod user_mapper;
"##,
    ), // [extra]
    (
        "crates/infrastructure/src/persistence/postgres/mapper/user_mapper.rs",
        r##"//! Maps `UserModel` ↔ domain `User`.

// TODO: implement `TryFrom<UserModel> for User` and `From<&User> for UserModel`,
// including enum <-> string conversions for `role` and `status`.
"##,
    ),
    (
        "crates/infrastructure/src/persistence/postgres/user_repository.rs",
        r##"//! `impl UserRepository for PostgresUserRepo`.

// TODO: implement the port on top of `sqlx::PgPool`.
"##,
    ),
    (
        "crates/infrastructure/src/persistence/postgres/auth_repository.rs",
        r##"//! `impl AuthRepository for PostgresAuthRepo`.

// TODO: implement session persistence on top of `sqlx::PgPool`.
"##,
    ),
    (
        "crates/infrastructure/src/persistence/postgres/unit_of_work.rs",
        r##"//! `impl UnitOfWork` on top of sqlx transactions.

// TODO: wrap `PgPool::begin()` / `commit()` / `rollback()`.
"##,
    ),
    (
        "crates/infrastructure/src/persistence/inmemory/mod.rs",
        r##"//! In-memory adapters — for tests and local development.

pub mod user_repository;
"##,
    ), // [extra]
    (
        "crates/infrastructure/src/persistence/inmemory/user_repository.rs",
        r##"//! In-memory `UserRepository` — zero external dependencies.

// TODO: implement with `RwLock<HashMap<uuid::Uuid, User>>`.
"##,
    ),
    (
        "crates/infrastructure/src/persistence/migration/mod.rs",
        r##"//! Embedded SQL migrations.
//!
//! Applied either by sqlx-cli (`scripts/migrate.sh`, which uses the
//! workspace-root `migrations/` folder) or by the `migrate` binary.
//! Embed these files with `include_str!` if you want them in the binary.
"##,
    ), // [extra]
    (
        "crates/infrastructure/src/persistence/migration/0001_init.up.sql",
        r##"-- Initial schema (embedded copy).
CREATE TABLE IF NOT EXISTS users (
    id            UUID PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    name          TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'User',
    status        TEXT NOT NULL DEFAULT 'Active',
    password_hash TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL
);
"##,
    ),
    (
        "crates/infrastructure/src/persistence/migration/0001_init.down.sql",
        r##"DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
"##,
    ),
    (
        "crates/infrastructure/src/cache/mod.rs",
        r##"//! Cache adapters.

pub mod inmemory_cache;
pub mod redis_cache;
"##,
    ),
    (
        "crates/infrastructure/src/cache/redis_cache.rs",
        r##"//! Redis cache adapter.

// TODO: implement with the `redis` crate (async, pooled connections).
"##,
    ),
    (
        "crates/infrastructure/src/cache/inmemory_cache.rs",
        r##"//! In-memory cache adapter (moka or a plain `HashMap`).

// TODO: implement with TTL support.
"##,
    ),
    (
        "crates/infrastructure/src/security/mod.rs",
        r##"//! Security adapters.

pub mod argon2_service;
pub mod jwt_service;
"##,
    ),
    (
        "crates/infrastructure/src/security/jwt_service.rs",
        r##"//! `impl TokenService` with JSON Web Tokens.

// TODO: implement with the `jsonwebtoken` crate (HS256 to start).
"##,
    ),
    (
        "crates/infrastructure/src/security/argon2_service.rs",
        r##"//! `impl PasswordService` with Argon2id (argon2 > bcrypt).

// TODO: implement with the `argon2` crate; tune m/t/p parameters.
"##,
    ),
    (
        "crates/infrastructure/src/messaging/mod.rs",
        r##"//! Messaging adapters (domain event publishers).

pub mod inmemory_publisher;
pub mod kafka_publisher;
pub mod rabbit_publisher;
"##,
    ),
    (
        "crates/infrastructure/src/messaging/kafka_publisher.rs",
        r##"//! `impl EventPublisher` for Kafka (rdkafka).

// TODO: implement with a producer per topic (e.g. `user.events`).
"##,
    ),
    (
        "crates/infrastructure/src/messaging/rabbit_publisher.rs",
        r##"//! `impl EventPublisher` for RabbitMQ (lapin).

// TODO: implement with a confirm-selected channel + exchange.
"##,
    ),
    (
        "crates/infrastructure/src/messaging/inmemory_publisher.rs",
        r##"//! `impl EventPublisher` that just logs events — for tests/dev.

// TODO: implement with a `tokio::sync::broadcast` channel.
"##,
    ),
    (
        "crates/infrastructure/src/logging/mod.rs",
        r##"//! Logging setup.

pub mod pii_redactor;
pub mod tracing_setup;
"##,
    ),
    (
        "crates/infrastructure/src/logging/tracing_setup.rs",
        r##"//! tracing-subscriber configuration (EnvFilter, JSON output in prod).

// TODO: implement `init()` with `tracing_subscriber::registry()` + layers.
"##,
    ),
    (
        "crates/infrastructure/src/logging/pii_redactor.rs",
        r##"//! Custom layer to redact PII (emails, tokens) from log output.

// TODO: implement a `tracing_subscriber::Layer` that rewrites event fields.
"##,
    ),
    (
        "crates/infrastructure/src/observability/mod.rs",
        r##"//! Observability adapters.

pub mod health;
pub mod metrics;
pub mod tracing;
"##,
    ),
    (
        "crates/infrastructure/src/observability/metrics.rs",
        r##"//! Prometheus metrics via the `metrics` façade.

// TODO: install an exporter and register counters/histograms.
"##,
    ),
    (
        "crates/infrastructure/src/observability/tracing.rs",
        r##"//! OpenTelemetry OTLP tracing export.

// TODO: build a tracer provider and install a `tracing` layer.
"##,
    ),
    (
        "crates/infrastructure/src/observability/health.rs",
        r##"//! Health registry — tracks DB, cache and broker connectivity.

// TODO: implement `HealthRegistry` with per-adapter checks.
"##,
    ),
    (
        "crates/infrastructure/tests/postgres_user_repository_test.rs",
        r##"//! Integration tests for `PostgresUserRepo` (needs a running Postgres).

// TODO: use `#[sqlx::test]` or testcontainers to provision a database.
"##,
    ),
    // ═══════════════════════════ crates/api ═══════════════════════════
    (
        "crates/api/Cargo.toml",
        r##"[package]
name = "api"
description = "Inbound HTTP adapter — Axum handlers, middleware, OpenAPI"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
application = { workspace = true }
domain      = { workspace = true }
shared      = { workspace = true }
axum        = "0.7"
tokio       = { workspace = true }
serde       = { workspace = true }
uuid        = { workspace = true }
tracing     = { workspace = true }

# TODO: enable as the layer is fleshed out:
# tower              = "0.5"
# tower-http         = { version = "0.6", features = ["trace", "cors", "compression-gzip"] }
# tower-governor     = "0.4"
# utoipa             = { version = "5", features = ["axum_extras", "uuid"] }
# utoipa-swagger-ui  = { version = "7", features = ["axum"] }
"##,
    ),
    (
        "crates/api/src/lib.rs",
        r##"//! API crate — the inbound HTTP adapter (Axum).
//!
//! Transport only: DTOs, handlers, routing, middleware, OpenAPI docs.
//! Every request is delegated to the application layer.

pub mod docs;
pub mod middleware;
pub mod router;
pub mod server;
pub mod state;
pub mod v1;
"##,
    ),
    (
        "crates/api/src/v1/mod.rs",
        r##"//! API version 1.

pub mod auth;
pub mod health;
pub mod user;
"##,
    ),
    (
        "crates/api/src/v1/user/mod.rs",
        r##"//! `/api/v1/users` endpoints.

pub mod dto;
pub mod handler;
pub mod mapper;
pub mod routes;
"##,
    ),
    (
        "crates/api/src/v1/user/handler.rs",
        r##"//! Axum handlers for the user resource.

use axum::extract::{Path, State};
use axum::Json;

use crate::state::app_state::AppState;

/// `GET /api/v1/users/:id`
pub async fn get_user(
    State(_state): State<AppState>,
    Path(_id): Path<uuid::Uuid>,
) -> Json<&'static str> {
    // TODO: delegate to `GetUserByIdUseCase`, map errors in
    // `middleware::error_handler`, map DTOs in `mapper`.
    Json("GET /users/:id — TODO")
}
"##,
    ),
    (
        "crates/api/src/v1/user/dto.rs",
        r##"//! Serde DTOs for the user endpoints (transport layer, not domain).

/// Request body for `POST /api/v1/users`.
#[derive(Debug, serde::Deserialize)]
pub struct CreateUserRequest {
    pub email: String,
    pub name: String,
    pub password: String,
}

/// Response body for user endpoints.
#[derive(Debug, serde::Serialize)]
pub struct UserResponse {
    pub id: uuid::Uuid,
    pub email: String,
    pub name: String,
}
"##,
    ),
    (
        "crates/api/src/v1/user/mapper.rs",
        r##"//! Maps transport DTOs ↔ application DTOs.

// TODO: `CreateUserRequest` → `CreateUserDto`, `UserResponseDto` → `UserResponse`.
"##,
    ),
    (
        "crates/api/src/v1/user/routes.rs",
        r##"//! Route table for the user resource.

use axum::routing::get;
use axum::Router;

use crate::state::app_state::AppState;
use crate::v1::user::handler;

/// Builds the `/api/v1/users` sub-router.
pub fn router() -> Router<AppState> {
    Router::new().route("/:id", get(handler::get_user))
}
"##,
    ),
    (
        "crates/api/src/v1/auth/mod.rs",
        r##"//! `/api/v1/auth` endpoints.

pub mod dto;
pub mod handler;
pub mod routes;
"##,
    ),
    (
        "crates/api/src/v1/auth/handler.rs",
        r##"//! Axum handlers for auth (`/register`, `/login`, `/verify`).

// TODO: delegate to `RegisterUserUseCase` / `LoginUserUseCase` / `VerifyTokenUseCase`.
"##,
    ),
    (
        "crates/api/src/v1/auth/dto.rs",
        r##"//! Serde DTOs for the auth endpoints.

// TODO: `RegisterRequest`, `LoginRequest`, `TokenResponse`.
"##,
    ),
    (
        "crates/api/src/v1/auth/routes.rs",
        r##"//! Route table for auth.

use axum::Router;

use crate::state::app_state::AppState;

/// Builds the `/api/v1/auth` sub-router.
pub fn router() -> Router<AppState> {
    Router::new() // TODO: .route("/register", post(...)).route("/login", post(...))
}
"##,
    ),
    (
        "crates/api/src/v1/health/mod.rs",
        r##"//! Health endpoints.

pub mod handler;
"##,
    ), // [extra]
    (
        "crates/api/src/v1/health/handler.rs",
        r##"//! `GET /healthz` — liveness/readiness probe.

use axum::http::StatusCode;

/// Liveness probe used by Docker/Kubernetes.
pub async fn healthz() -> StatusCode {
    // TODO: consult `infrastructure::observability::health::HealthRegistry`.
    StatusCode::OK
}
"##,
    ),
    (
        "crates/api/src/middleware/mod.rs",
        r##"//! HTTP middleware stack.

pub mod auth;
pub mod error_handler;
pub mod logging;
pub mod rate_limit;
pub mod security_headers;
pub mod tracing;
"##,
    ),
    (
        "crates/api/src/middleware/auth.rs",
        r##"//! JWT extractor middleware.

// TODO: implement `FromRequestParts` for an `AuthUser` extractor that
// verifies the bearer token via `TokenService`.
"##,
    ),
    (
        "crates/api/src/middleware/error_handler.rs",
        r##"//! `IntoResponse` impls for domain/application errors.

// TODO: map `DomainError`/`AppError` to proper HTTP status codes
// without leaking internals.
"##,
    ),
    (
        "crates/api/src/middleware/logging.rs",
        r##"//! Request logging via tower-http's `TraceLayer`.

// TODO: add `TraceLayer::new_for_http()` to the router.
"##,
    ),
    (
        "crates/api/src/middleware/rate_limit.rs",
        r##"//! Rate limiting via tower-governor.

// TODO: per-IP governor layer with sensible defaults.
"##,
    ),
    (
        "crates/api/src/middleware/security_headers.rs",
        r##"//! Custom layer that injects security headers.

// TODO: add HSTS, X-Content-Type-Options, a strict CSP, …
"##,
    ),
    (
        "crates/api/src/middleware/tracing.rs",
        r##"//! OpenTelemetry instrumentation for inbound requests.

// TODO: propagate/extract W3C `traceparent` context.
"##,
    ),
    (
        "crates/api/src/docs/mod.rs",
        r##"//! OpenAPI documentation (utoipa).

pub mod openapi;
pub mod redoc;
pub mod swagger_ui;
"##,
    ),
    (
        "crates/api/src/docs/openapi.rs",
        r##"//! `utoipa::OpenApi` derive for the whole API.

// TODO: annotate handlers/DTOs with `#[utoipa::path]` / `#[derive(ToSchema)]`
// and compose them here.
"##,
    ),
    (
        "crates/api/src/docs/swagger_ui.rs",
        r##"//! Swagger UI handler (utoipa-swagger-ui).

// TODO: serve `/docs/swagger-ui`.
"##,
    ),
    (
        "crates/api/src/docs/redoc.rs",
        r##"//! ReDoc handler.

// TODO: serve `/docs/redoc` backed by the generated OpenAPI JSON.
"##,
    ),
    (
        "crates/api/src/state/mod.rs",
        r##"//! Shared application state.

pub mod app_state;
"##,
    ), // [extra]
    (
        "crates/api/src/state/app_state.rs",
        r##"//! `AppState` — holds `Arc<dyn Port>` dependencies for the handlers.

use std::sync::Arc;

use domain::user::port::password_service::PasswordService;
use domain::user::port::user_repository::UserRepository;

/// Injected into every handler via `axum::extract::State`.
///
/// The state knows only the *ports* — the composition root
/// (`crates/bin/api`) decides which adapters implement them.
#[derive(Clone)]
pub struct AppState {
    pub user_repository: Arc<dyn UserRepository>,
    pub password_service: Arc<dyn PasswordService>,
}
"##,
    ),
    (
        "crates/api/src/router.rs",
        r##"//! Axum router composition.

use axum::routing::get;
use axum::Router;

use crate::state::app_state::AppState;
use crate::v1;

/// Composes the complete application router.
pub fn router(state: AppState) -> Router {
    Router::new()
        .route("/healthz", get(crate::v1::health::handler::healthz))
        .nest("/api/v1/users", v1::user::routes::router())
        .nest("/api/v1/auth", v1::auth::routes::router())
        // TODO: middleware::logging, rate_limit, security_headers, docs…
        .with_state(state)
}
"##,
    ),
    (
        "crates/api/src/server.rs",
        r##"//! Server bootstrap.

use std::net::SocketAddr;

use tokio::net::TcpListener;

use crate::router::router;
use crate::state::app_state::AppState;

/// Binds `addr` and serves the API until shutdown.
pub async fn serve_api(
    addr: SocketAddr,
    state: AppState,
) -> Result<(), Box<dyn std::error::Error>> {
    let listener = TcpListener::bind(addr).await?;
    axum::serve(listener, router(state)).await?;
    Ok(())
}
"##,
    ),
    (
        "crates/api/tests/user_api_test.rs",
        r##"//! API integration tests — no database required.

// TODO: build the router with in-memory adapters and drive it with
// `tower::ServiceExt::oneshot`.
"##,
    ),
    // ═══════════════════════════ crates/config ═══════════════════════════
    (
        "crates/config/Cargo.toml",
        r##"[package]
name = "config"
description = "figment-based configuration loading"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
figment = { version = "0.10", features = ["yaml"] }
serde   = { workspace = true }
"##,
    ),
    (
        "crates/config/src/lib.rs",
        r##"//! Configuration loading via figment (file + profile + env overrides).

pub mod app_config;
pub mod database;
pub mod observability;
pub mod security;
pub mod server;
"##,
    ),
    (
        "crates/config/src/app_config.rs",
        r##"//! Root configuration — `config.yaml` + `config.<profile>.yaml` + env.

use figment::providers::{Env, Format, Yaml};
use figment::Figment;

use crate::database::DatabaseConfig;
use crate::observability::ObservabilityConfig;
use crate::security::SecurityConfig;
use crate::server::ServerConfig;

/// The full application configuration.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct AppConfig {
    pub server: ServerConfig,
    pub database: DatabaseConfig,
    pub security: SecurityConfig,
    pub observability: ObservabilityConfig,
}

impl AppConfig {
    /// Loads `config.yaml`, then `config.<profile>.yaml`, then `APP__*` env vars.
    ///
    /// `profile` is typically `"dev"`, `"prod"`, …
    pub fn load(profile: &str) -> Result<Self, figment::Error> {
        Figment::new()
            .merge(Yaml::file("config.yaml"))
            .merge(Yaml::file(format!("config.{profile}.yaml")))
            .merge(Env::prefixed("APP_").split("__"))
            .extract()
    }
}
"##,
    ),
    (
        "crates/config/src/database.rs",
        r##"//! Database configuration.

/// PostgreSQL connection settings.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct DatabaseConfig {
    pub url: String,
    pub max_connections: u32,
}
"##,
    ),
    (
        "crates/config/src/server.rs",
        r##"//! HTTP server configuration.

/// Bind settings for the API server.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct ServerConfig {
    pub host: String,
    pub port: u16,
}
"##,
    ),
    (
        "crates/config/src/security.rs",
        r##"//! Security configuration.

/// JWT / password hashing parameters.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct SecurityConfig {
    pub jwt_secret: String,
    pub access_token_ttl_secs: i64,
}
"##,
    ),
    (
        "crates/config/src/observability.rs",
        r##"//! Observability configuration.

/// Logging / metrics / tracing toggles.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct ObservabilityConfig {
    pub log_level: String,
    pub metrics_enabled: bool,
    pub tracing_enabled: bool,
}
"##,
    ),
    // ═══════════════════════════ crates/shared ═══════════════════════════
    (
        "crates/shared/Cargo.toml",
        r##"[package]
name = "shared"
description = "Cross-cutting utilities — AppError, AppResult, pagination, validation"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
thiserror = { workspace = true }
serde     = { workspace = true }
# validator = "0.19"   # TODO: enable when validation.rs is implemented
"##,
    ),
    (
        "crates/shared/src/lib.rs",
        r##"//! Shared utilities used by every layer.

pub mod error;
pub mod pagination;
pub mod result;
pub mod validation;
"##,
    ),
    (
        "crates/shared/src/error.rs",
        r##"//! `AppError` — the top-level error type (thiserror).

/// Application-wide error type for adapters and the composition root.
#[derive(Debug, thiserror::Error)]
pub enum AppError {
    #[error("configuration error: {0}")]
    Config(String),

    #[error("validation error: {0}")]
    Validation(String),

    #[error("not found: {0}")]
    NotFound(String),

    #[error("internal error: {0}")]
    Internal(String),
}
"##,
    ),
    (
        "crates/shared/src/result.rs",
        r##"//! Convenient result alias.

/// `AppResult<T>` — used across the workspace.
pub type AppResult<T> = Result<T, crate::error::AppError>;
"##,
    ),
    (
        "crates/shared/src/pagination.rs",
        r##"//! Pagination helpers for the transport layer.

/// Inbound page request parameters.
#[derive(Debug, Clone, Copy, serde::Deserialize)]
pub struct PageParams {
    /// 1-based page number.
    pub page: u32,
    /// Items per page.
    pub per_page: u32,
}
"##,
    ),
    (
        "crates/shared/src/validation.rs",
        r##"//! Helpers around the `validator` crate.

// TODO: add reusable validation rules / guard clauses.
"##,
    ),
    // ═══════════════════════════ crates/bin ═══════════════════════════
    (
        "crates/bin/api/Cargo.toml",
        r##"[package]
name = "api-server"
description = "HTTP API binary — the composition root"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
api            = { workspace = true }
application    = { workspace = true }
domain         = { workspace = true }
infrastructure = { workspace = true }
config         = { workspace = true }
shared         = { workspace = true }
tokio          = { workspace = true }
tracing        = { workspace = true }
"##,
    ),
    (
        "crates/bin/api/src/main.rs",
        r##"//! API binary entry point — the composition root.
//!
//! This is the *only* place where concrete adapters are chosen and
//! wired into the domain's ports.

use std::net::SocketAddr;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // 1. Configuration.
    let cfg = config::app_config::AppConfig::load("dev")?;

    // 2. Compose the hexagon: pick adapters, inject into ports, e.g.
    //    let user_repository: Arc<dyn UserRepository> = Arc::new(
    //        infrastructure::persistence::postgres::user_repository::PostgresUserRepo::new(pool));
    //    let password_service: Arc<dyn PasswordService> = Arc::new(
    //        infrastructure::security::argon2_service::Argon2Service::default());
    //    let state = api::state::app_state::AppState { user_repository, password_service };

    // 3. Serve (uncomment once the adapters above exist):
    let addr = SocketAddr::from(([0, 0, 0, 0], cfg.server.port));
    println!("api-server: would listen on {addr} — TODO: wire real adapters");
    // api::server::serve_api(addr, state).await?;

    Ok(())
}
"##,
    ),
    (
        "crates/bin/worker/Cargo.toml",
        r##"[package]
name = "worker"
description = "Event worker binary — consumes domain events"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
application    = { workspace = true }
domain         = { workspace = true }
infrastructure = { workspace = true }
config         = { workspace = true }
tokio          = { workspace = true }
tracing        = { workspace = true }
"##,
    ),
    (
        "crates/bin/worker/src/main.rs",
        r##"//! Event worker binary — consumes domain events and reacts to them.

#[tokio::main]
async fn main() {
    // TODO: subscribe via the messaging adapter (Kafka/RabbitMQ)
    // and dispatch events to handlers.
    println!("worker: TODO — consume domain events and dispatch handlers");
}
"##,
    ),
    (
        "crates/bin/migrate/Cargo.toml",
        r##"[package]
name = "migrate"
description = "Migration CLI — applies SQL migrations"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
config = { workspace = true }
tokio  = { workspace = true }
# sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "postgres", "migrate"] }
"##,
    ),
    (
        "crates/bin/migrate/src/main.rs",
        r##"//! Migration CLI — applies the SQL migrations in `migrations/`.

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // TODO:
    //   let cfg = config::app_config::AppConfig::load("dev")?;
    //   let pool = sqlx::postgres::PgPoolOptions::new()
    //       .max_connections(1)
    //       .connect(&cfg.database.url)
    //       .await?;
    //   sqlx::migrate!("./migrations").run(&pool).await?;
    println!("migrate: TODO — apply ./migrations via sqlx::migrate!");
    Ok(())
}
"##,
    ),
    // ═══════════════════════ migrations / tests / benches ═══════════════════════
    (
        "migrations/20260101000000_init.sql",
        r##"-- Initial schema (sqlx migration).
CREATE TABLE IF NOT EXISTS users (
    id            UUID PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    name          TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'User',
    status        TEXT NOT NULL DEFAULT 'Active',
    password_hash TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL
);
"##,
    ),
    (
        "migrations/20260102000000_seed.sql",
        r##"-- Seed data (dev only).
INSERT INTO users (id, email, name, role, status, password_hash)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'admin@example.com',
    'Admin',
    'Admin',
    'Active',
    '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_ME'
)
ON CONFLICT (email) DO NOTHING;
"##,
    ),
    (
        "tests/common/mod.rs",
        r##"//! Shared fixtures for workspace-level integration tests.

// TODO: testcontainers (Postgres, Redis) bootstrapping and in-memory fakes.
"##,
    ),
    (
        "tests/e2e/user_flow.rs",
        r##"//! E2E: register → login → verify → list → delete.

// TODO: run against the real API (or the composed router) over HTTP.
"##,
    ),
    (
        "benches/user_benchmarks.rs",
        r##"//! Benchmarks (criterion).

// TODO: convert to a criterion benchmark:
//
//     use criterion::{criterion_group, criterion_main, Criterion};
//
//     fn bench_user_registration(c: &mut Criterion) {
//         c.bench_function("user_registration", |b| b.iter(|| {
//             // domain::user::entity::user::User::register(...)
//         }));
//     }
//
//     criterion_group!(benches, bench_user_registration);
//     criterion_main!(benches);
"##,
    ),
    // ═══════════════════════════ scripts ═══════════════════════════
    (
        "scripts/migrate.sh",
        r##"#!/usr/bin/env bash
set -euo pipefail
# Applies SQL migrations (sqlx-cli) from ./migrations.
export DATABASE_URL="${DATABASE_URL:-postgres://postgres:postgres@localhost:5432/hexagonal}"
sqlx migrate run --source migrations
"##,
    ),
    (
        "scripts/seed.sh",
        r##"#!/usr/bin/env bash
set -euo pipefail
# Applies seed data (dev only).
export DATABASE_URL="${DATABASE_URL:-postgres://postgres:postgres@localhost:5432/hexagonal}"
psql "$DATABASE_URL" -f migrations/20260102000000_seed.sql
"##,
    ),
    (
        "scripts/generate-openapi.sh",
        r##"#!/usr/bin/env bash
set -euo pipefail
# Dumps the OpenAPI spec to docs/openapi.json.
# TODO: implement `--dump-openapi` in the api-server binary (utoipa).
echo "TODO: implement --dump-openapi in api-server (utoipa::OpenApi)" >&2
exit 1
"##,
    ),
    (
        "scripts/health-check.sh",
        r##"#!/usr/bin/env bash
set -euo pipefail
# Liveness check against the API.
HOST="${HOST:-localhost}"
PORT="${PORT:-8080}"
curl --fail --silent "http://${HOST}:${PORT}/healthz" && echo " OK"
"##,
    ),
    // ═══════════════════════════ deployments ═══════════════════════════
    (
        "deployments/docker/Dockerfile",
        r##"# Multi-stage cargo build (cargo-chef for dependency caching).
FROM rust:1.83 AS chef
RUN cargo install cargo-chef --locked
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release -p api-server

FROM debian:bookworm-slim AS runtime
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/api-server /usr/local/bin/api-server
COPY config.yaml /app/config.yaml
WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/api-server"]
"##,
    ),
    (
        "deployments/docker/docker-compose.yml",
        r##"services:
  api:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_DATABASE__URL: postgres://postgres:postgres@db:5432/hexagonal
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hexagonal
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
  cache:
    image: redis:7
    ports:
      - "6379:6379"
"##,
    ),
    (
        "deployments/kubernetes/deployment.yaml",
        r##"apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexagonal-api
  labels:
    app: hexagonal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hexagonal-api
  template:
    metadata:
      labels:
        app: hexagonal-api
    spec:
      containers:
        - name: api
          image: hexagonal-api:0.1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
"##,
    ),
    (
        "deployments/kubernetes/service.yaml",
        r##"apiVersion: v1
kind: Service
metadata:
  name: hexagonal-api
spec:
  selector:
    app: hexagonal-api
  ports:
    - port: 80
      targetPort: 8080
"##,
    ),
    (
        "deployments/kubernetes/ingress.yaml",
        r##"apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hexagonal-api
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hexagonal-api
                port:
                  number: 80
"##,
    ),
    (
        "deployments/kubernetes/hpa.yaml",
        r##"apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hexagonal-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hexagonal-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
"##,
    ),
    // ═══════════════════════════ docs ═══════════════════════════
    (
        "docs/ARCHITECTURE.md",
        r##"# Architecture

Hexagonal architecture (a.k.a. Ports & Adapters) over a Cargo workspace.

## The dependency rule

    api ──▶ application ──▶ domain ◀── infrastructure
                        (ports)

- **domain** — entities, value objects, domain events, and *ports* (traits).
  Zero framework dependencies.
- **application** — use cases (commands/queries) that orchestrate the domain
  through its ports. Also framework-free.
- **infrastructure** — *outbound* adapters implementing the ports:
  Postgres (sqlx), Redis, Argon2, JWT, Kafka/RabbitMQ, tracing, metrics.
- **api** — *inbound* adapter: Axum HTTP transport, DTOs, middleware, OpenAPI.
- **crates/bin/** — composition roots that wire adapters into ports.

Dependencies point **inwards** only; the domain never knows who calls it.
"##,
    ),
    (
        "docs/DEVELOPMENT.md",
        r##"# Development

## Prerequisites

- Rust (pinned via `rust-toolchain.toml`)
- Docker & docker-compose (Postgres, Redis)
- sqlx-cli: `cargo install sqlx-cli --no-default-features --features rustls,postgres`

## Getting started

    cp secrets/.env.example secrets/.env
    docker compose -f deployments/docker/docker-compose.yml up -d db cache
    ./scripts/migrate.sh
    cargo run -p api-server

## Common tasks

Run `make help`. Notably: `make test`, `make lint`, `make fmt`.

## Conventions

- Formatting/linting: `.rustfmt.toml`, `.clippy.toml`
- Architecture decisions: `docs/adr/`
"##,
    ),
    (
        "docs/adr/0001-hexagonal-rust.md",
        r##"# ADR 0001 — Hexagonal architecture in Rust

Status: accepted

## Context

We need a testable, framework-independent core for a user/auth service.

## Decision

Apply ports & adapters: the domain defines traits (ports) for persistence,
security and messaging; adapters in `infrastructure` implement them; the
application layer orchestrates via use cases; transport lives in `api`.

## Consequences

+ The domain compiles and tests without a database or HTTP server.
+ Adapters are replaceable (Postgres ⇄ in-memory, Kafka ⇄ in-memory).
− More crates and indirection than a layered single crate.
"##,
    ),
    (
        "docs/adr/0002-workspace-layout.md",
        r##"# ADR 0002 — Cargo workspace layout

Status: accepted

## Context

One crate per layer maximises compile parallelism and makes illegal
dependencies fail at compile time (e.g. `domain` cannot import `axum`).

## Decision

`crates/{domain,application,infrastructure,api,config,shared}` plus thin
binaries in `crates/bin/{api,worker,migrate}`. Shared dependency versions
are centralised in the root `[workspace.dependencies]`.

## Consequences

+ Enforced layering, faster incremental builds.
− Slightly more boilerplate for cross-cutting concerns.
"##,
    ),
    // ═══════════════════════ logs / secrets ═══════════════════════
    ("logs/.gitkeep", ""),
    (
        "secrets/.gitignore",
        r##"# Ignore everything in secrets/ except these two files.
*
!.gitignore
!.env.example
"##,
    ),
    (
        "secrets/.env.example",
        r##"# Copy to secrets/.env (or export) and fill in real values.
# NEVER commit real secrets — this directory is gitignored.

APP_DATABASE__URL=postgres://postgres:postgres@localhost:5432/hexagonal
APP_SECURITY__JWT_SECRET=replace-with-a-long-random-string
"##,
    ),
];

fn main() -> ExitCode {
    let root = PathBuf::from(
        std::env::args()
            .nth(1)
            .unwrap_or_else(|| DEFAULT_ROOT.to_string()),
    );

    println!(
        "Scaffolding hexagonal architecture workspace in: {}\n",
        root.display()
    );

    match scaffold(&root) {
        Ok((created, skipped, dirs)) => {
            println!(
                "\nDone: {created} file(s) created ({skipped} skipped as existing) across {dirs} directories."
            );
            println!("\nNext steps:");
            println!("  cd {}", root.display());
            println!("  cargo build --workspace     # compiles the skeleton");
            println!("  cargo test -p domain       # 2 real tests (Email parsing) pass");
            ExitCode::SUCCESS
        }
        Err(err) => {
            eprintln!("\nError: {err}");
            ExitCode::FAILURE
        }
    }
}

fn scaffold(root: &Path) -> io::Result<(usize, usize, usize)> {
    let mut created = 0;
    let mut skipped = 0;

    for (rel, contents) in FILES {
        let path = root.join(rel);

        // Directories are implied by the file paths.
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        if path.exists() {
            println!("  ·  {rel}  (exists, skipped)");
            skipped += 1;
            continue;
        }

        fs::write(&path, contents)?;
        println!("  +  {rel}");
        created += 1;
    }

    // Mark shell scripts executable on Unix.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        for (rel, _) in FILES {
            if rel.ends_with(".sh") {
                let path = root.join(rel);
                let mut perms = fs::metadata(&path)?.permissions();
                perms.set_mode(perms.mode() | 0o755);
                fs::set_permissions(&path, perms)?;
            }
        }
    }

    // Count distinct directories for the summary (+ the root itself).
    let dirs: BTreeSet<&Path> = FILES
        .iter()
        .filter_map(|(rel, _)| Path::new(rel).parent())
        .collect();

    Ok((created, skipped, dirs.len() + 1))
}
